language: 
  - c

compiler: 
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang cmake

branches:
  only:
    - devel

script:
  - rm -rf build/
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest 
  - sudo make install

